---
title: Statistical analysis of the count matrix of extracted reactions
author: Jan Taubenheim
date: "`r Sys.Date()`"
output: 
        html_document:
                toc: true
                theme: united
---


```{r setLogfile, eval =F}

log <- file(snakemake@log[[1]], open = "wt")
sink(log)
sink(log, type = "message")

```


```{r loadLibraries}

knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.width = 10, fig.height=5)

require(ggplot2)
require(data.table)
require(lme4)
require(lqmm)
require(car)
require(cowplot)
require(DT)
require(pheatmap)
require(limma)
require(cluster)

```

```{r debug, eval=FALSE, include =FALSE}

# This section is only for debugging purposes
setClass("snakemake", representation(input = "list", output = "list"))
snakemake <- new("snakemake", 
                    input = list(
                        rxnCount = "results/data/ModelAnalysis/MatjesAbsorption.colormore22-rxnIdMat.csv",
                        subSysCount = "results/data/ModelAnalysis/MatjesAbsorption.colormore22-SubSysMat.csv",
                        lqmmModels = "results/data/FVA/MatjesAbsorption.colormore22-LQMMmodelsRangeFVA_zeroBiomass.csv",
                        rxn_stats = "results/data/FVA/MatjesAbsorption.colormore22-distFVA_zeroBiomassvs~HB_Mayo_impu-PERMANOVAmodels.csv",
                        fva = "results/data/FVA/MatjesAbsorption.colormore22-FVA_zeroBiomass.RDS",
                        distFiles = "results/data/FVA/MatjesAbsorption.colormore22_zeroBiomass_Rxndist.tar.gz",
                        meta = "resources/META_emed_future.csv",
                        clinic = "resources/ClinicalData.csv",
                        subsysTable = "resources/Subsystems.csv",
                        sampleBlacklist = "resources/sampleBlacklist.csv",
                        GPR = "resources/colormore22_GPR.csv"
                    ),
                    output = list(
                        html = "results/reports/MatjesAbsorption.colormore22-Natrix_analyseRxnCounts.html"
                    )
                )

```


```{r}

meta <- fread(snakemake@input[["meta"]])
meta[,PatientID_Time := paste(PatientID, Time_seq, sep ="_")]
meta <- meta[Time_seq != -1,]
clinic <- fread(snakemake@input[["clinic"]], drop=1)
meta <- merge(meta,clinic, by="PatientID_Time", all.x=TRUE, suffix = c(".meta",""))
#meta_merge <- merge(meta,clinic, all.x=TRUE)

subSys <- fread(snakemake@input[["subSysCount"]])
subSysCount <- as.matrix(subSys[,-1, with =F])
rownames(subSysCount) <- gsub(" ","_",unlist(subSys[,1]))
rxns <- fread(snakemake@input[["rxnCount"]])
rxnCount <- as.matrix(rxns[,-1,with=F ])
rownames(rxnCount) <- gsub(" ","_",unlist(rxns[,1]))
subSystems <- fread(snakemake@input[["subsysTable"]])
GPR <- fread(snakemake@input[["GPR"]])

# remove degraded samples
blcklst <- fread(snakemake@input[["sampleBlacklist"]])
blckSmpls <- blcklst[relevance < 2, Sample]

meta <- meta[!(SeqID %in% blckSmpls),]
subSysCount <- subSysCount[,!(colnames(rxnCount) %in% blckSmpls)]
rxnCount <- rxnCount[,!(colnames(rxnCount) %in% blckSmpls)]
meta <- meta[SeqID %in% colnames(rxnCount),]

lqmmModels <- fread(snakemake@input[["lqmmModels"]])
rxnDistStats <- fread(snakemake@input[["rxn_stats"]])

fva <- readRDS(snakemake@input[["fva"]])
distTar <- snakemake@input[["distFiles"]]

```


```{r rxnHBMayo}


# than we can still use a simple wilcox test for each reaction (present/absence) to test association with HB_Mayo

trxnCount <- data.table(t(rxnCount), keep.rownames=TRUE)
rxn_wilcox <- merge(meta[Tissue == "Biopsy" & !is.na(HB_Mayo_impu),], 
                    trxnCount, 
                    by.x ="SeqID",
                    by.y="rn")

rxn <- rownames(rxnCount)[apply(rxnCount,1,sum)>0]
wcxTest <- data.frame(
                    log2FC = rep(NA, length(rxn)),
                    pval = rep(NA,length(rxn)),
                    padj = rep(NA,length(rxn)),
                    row.names = rxn)
for(r in rxn){
    sel <- rxn_wilcox[[r]]
    if(sum(sel) < length(sel)-3 & sum(sel) > 3){
        wcx <- wilcox.test(rxn_wilcox[sel, HB_Mayo_impu],
                           rxn_wilcox[!sel,HB_Mayo_impu])
        wcxTest[r,"pval"] <- wcx[["p.value"]]
        wcxTest[r,"log2FC"] <- mean(log2(rxn_wilcox[sel, HB_Mayo_impu]+1)) -
                           mean(log2(rxn_wilcox[!sel,HB_Mayo_impu]+1))
                    }
}
wcxTest[["padj"]] <- p.adjust(wcxTest[["pval"]], method = "BH")
wcxTest <- data.table(wcxTest,keep.rownames=TRUE)
wcxTest[,absLog2FC := abs(log2FC)]
wcxTest[,rxn_plot := factor(rn, level = rn[order(log2FC)])]

```

```{r venn}

# creating a matrix for a venn diagram
vennMat <- matrix(FALSE,nrow=nrow(subSystems), ncol = 3, dimnames = list(rxns = subSystems[["rxns"]], test = c("presence","range","distance")))
vennMat[wcxTest[padj <= 0.05, rn], "presence"] <- TRUE
vennMat[lqmmModels[padj <= 0.05, variable], "range"] <- TRUE
vennMat[rxnDistStats[padj <= 0.05 & Variable == "HB_Mayo_impu", Rxn], "distance"] <- TRUE

# plotting the venn diagram
limma::vennDiagram(vennMat)


# looking into the middle of it
vennSig <- vennMat[apply(vennMat,1,sum) == ncol(vennMat),]

vennSig <- data.frame(vennSig)
setkey(subSystems, "rxns")
vennSig[["Subsystems"]] <- subSystems[rownames(vennSig),subSys]

# add the metrics
setkey(wcxTest,"rn")
vennSig[["Presence_log2FC"]] <- wcxTest[rownames(vennSig),log2FC]
setkey(lqmmModels,"variable")
vennSig[["Range_coeff"]] <- as.numeric(lqmmModels[rownames(vennSig),coefficient])
setkey(rxnDistStats,"Rxn")
vennSig[["Dist_R2"]] <- rxnDistStats[rownames(vennSig),R2]

# plot the wilcoxon fold change
pp_log2FC <-ggplot(data = vennSig, aes(y = Subsystems, x = Presence_log2FC, color = Subsystems)) +
    geom_vline(xintercept = 0,linetype=2)+
    geom_jitter(height=0.25, width = 0,size=2) +
    theme_bw() +
    theme(legend.position = "none")
# plot the lqmm coefficient
pp_coeff<-ggplot(data = vennSig, aes(y = Subsystems, x = as.numeric(Range_coeff),color = Subsystems)) +
    geom_vline(xintercept = 0,linetype=2)+
    geom_jitter(height=0.25, width = 0,size=2)+
    xlab("Coefficient of LQMM model")+
    theme_bw() +
    theme(legend.position = "none",
    axis.text.y = element_blank(),
    axis.title.y = element_blank())
# plot the variance in distance explained by the variable tested
pp_R2 <-ggplot(data = vennSig, aes(y = Subsystems, x = Dist_R2,color =Subsystems)) +
    geom_jitter(height=0.25, width = 0,size=2)+
    xlab("Distance variance explained by HB/Mayo")+
    theme_bw() +
    theme(legend.position = "none",
    axis.text.y = element_blank(),
    axis.title.y = element_blank())

pp <- cowplot::plot_grid(pp_log2FC,pp_coeff,pp_R2,ncol=3,rel_widths = c(1.5,1,1))
pp



pp_log2FCbar <-ggplot(data = vennSig[order(vennSig[["Presence_log2FC"]],vennSig[["Subsystems"]]),], aes(x=1:nrow(vennSig),y = Presence_log2FC, fill = Subsystems)) +
    geom_bar(stat="identity")+
    theme_bw() +
    xlab("Rxns")+
    ylab("Fold change of HB/Mayo score on presence of rxn")+
    theme(axis.text.x = element_blank())

vennSig2 <- merge(data.table(vennSig, keep.rownames =TRUE), GPR, by.x="rn",by.y="rxn",keep.x=TRUE)

# function to count the genes in a string
countGPRgenes <- function(pattern, text){
    # @text - a vector of character strings to look for the pattern
    # @pattern - a pattern to look for in the text
    # returns - a list of the same length as text with the number of unique patterns
    result <- list()
    cnt <- 0
    for(t in text){
        cnt <- cnt+1
        srch <- gregexpr(pattern, t)[[1]]
        res <- c()
        for(i in 1:length(srch)){
            srch_len <- attributes(srch)[["match.length"]][i]
            res<- c(res,substr(t,srch[i],srch[i]+srch_len-1))
        }
    result[[cnt]] <- unique(res)
    }
    return(result)
}




vennPlot <- vennSig2[,.(numberRxn = .N,
                        mean_log2FC = mean(Presence_log2FC),
                        mean_coeff = mean(Range_coeff),
                        mean_R2 = mean(as.numeric(Dist_R2))), 
                    by = Subsystems]

# extract the number of genes involved
ngenes <- sapply(countGPRgenes("HGNC:\\d+",unlist(vennSig2[,.(n_genes = gsub("\\s","",paste(GPR,collapse=","))),by="Subsystems"][,2])), length)
vennPlot[,n_genes := ngenes]


pp <- ggplot(data = vennPlot, aes(y=mean_coeff, x = mean_log2FC, size = mean_R2, color = Subsystems)) +
    geom_point()
pp

pp_genesbar <- ggplot(data = vennPlot, aes(x=Subsystems, y=n_genes, fill = Subsystems)) +
    geom_bar(stat="identity") +
    ylab("Number of genes involved")+
    theme_bw() +
    theme(legend.position = "none",
          axis.text.x = element_blank())

pp_inset <- ggdraw() +
    draw_plot(pp_log2FCbar) +
    draw_plot(pp_genesbar, x=0.40,y=0.07, width=0.3,height=0.3)
pp_inset

```

This is the list of significant genes from all analysis

```{r Table}

datatable(vennSig2)

```

# Plotting of the association

Having a list of genes, we can now look into the relation of the ranges to the HB/Mayo score.

```{r associationPlotting}

sig_rxn <- vennSig2[,rn]
fva_min <- reshape2::melt(fva[sig_rxn,,"min"])
fva_max <- reshape2::melt(fva[sig_rxn,,"max"])
fva_range <-reshape2::melt(fva[sig_rxn,,"range"])
fva_center <-reshape2::melt(fva[sig_rxn,,"center"])

fva_dat <- merge(fva_min,fva_max,suffix = c(".min",".max"),by=c("rxn","sample"))
fva_dat <- merge(fva_dat,fva_center,by=c("rxn","sample"))
fva_dat <- merge(fva_dat,fva_range,suffix = c(".center",".range"),by=c("rxn","sample"))


fva_dat <- reshape2::melt(fva_dat, id.vals = paste0("value.",dimnames(fva)[3]))
fva_dat[["variable"]] <- gsub("^value\\.","",fva_dat[["variable"]])

fva_dat <- merge(fva_dat, meta, by.x="sample",by.y="SeqID")
fva_dat <- merge(fva_dat, vennSig2, by.x="rxn",by.y="rn")
fva_dat <- data.table(fva_dat)


# select only those reaction which are not based on the same GPR
rxnSelection <- vennSig2[!duplicated(GPR),rn]
rdr <- vennSig2[,rn][order(vennSig2[,Subsystems])]
rdr <- split(rdr, ceiling(seq_along(rdr)/20))

# dotplots
for(rxnSelection in rdr){
fva_plot <- fva_dat[rxn %in% rxnSelection,]
pp <- ggplot(fva_plot[variable %in% c("min","max"),], aes(x=HB_Mayo_impu, y=value, color=variable)) +
    geom_jitter(height= 0, width=0.25,alpha=0.5) +
    geom_smooth()+
    facet_wrap(~rxn, scale ="free")
print(pp)
}

```


# Clustering

Using only the significant reactions we can try to cluster the data once more.

```{r clustering}


distFiles <- untar(distTar, list=TRUE)
f <- sapply(paste0("/",vennSig2[,rn],".csv"),
            grep,
            x = distFiles,
            value=TRUE,
            fixed=TRUE)
tmpd <- file.path(tempdir(),"untar")
dir.create(tmpd)
untar(distTar, files = unlist(f),exdir = tmpd)
distMat <- lapply(file.path(tmpd,unlist(f)),read.csv,row.names=1)
distMat <- simplify2array(lapply(distMat,as.matrix))
dimnames(distMat)[[3]] <- vennSig2[,rn]
unlink(tmpd, recursive=TRUE)

distAll <- apply(distMat,1:2,mean)
distscl <- cmdscale(as.dist(distAll))

distscl <- merge(meta,data.table(distscl, keep.rownames=TRUE), by.x="SeqID", by.y="rn")

pp <- ggplot(distscl, aes(x=V1,y=V2, color = HB_Mayo_impu<5, shape = Response,label = Response)) +
             geom_text() +
             facet_wrap(~Diagnosis)
pp

pp <- ggplot(distscl, aes(x=V1,y=V2, color = as.factor(Time_seq), shape = HB_Mayo_impu<5)) +
             geom_point(size=3,alpha=0.5)
pp

pp <- ggplot(distscl, aes(x=HB_Mayo_impu, y=V1)) +
    geom_point()+
    geom_smooth()
pp

pp <- ggplot(distscl, aes(x=HB_Mayo_impu, y=V2)) +
    geom_point()+
    geom_smooth()
pp

with(distscl,cor.test(HB_Mayo_impu,V1,method="kendall"))
with(distscl,cor.test(HB_Mayo_impu,V2,method="kendall"))


distclst <- pam(distAll, k = 2, diss = TRUE)
setkey(distscl, "SeqID")
distscl[names(distclst[["clustering"]]), PAMs := distclst[["clustering"]]]

pp <- ggplot(distscl, aes(x=factor(PAMs), y = HB_Mayo_impu)) +
    geom_boxplot()
pp
wilcox.test(data=distscl, HB_Mayo_impu~factor(PAMs))

# do a plot of all reactions singular
for(i in 1:length(rdr)){
    rxns <-rdr[[i]]
    distRy <- distMat[,,rxns]
    dstscl <- lapply(rxns,function(x) cmdscale(as.dist(distRy[,,x])))
    names(dstscl) <- rxns
    for(reac in seq_along(dstscl)){
        dstscl[[reac]] <- cbind(data.frame(dstscl[[reac]]),rxn = names(dstscl)[reac],SeqID = rownames(dstscl[[reac]]))
    }
    dstscl <- data.table(do.call(rbind, dstscl))
    dstscls <- merge(meta, dstscl, by="SeqID")

    pp <- ggplot(dstscls, aes(x=X1,y=X2, color = HB_Mayo_impu<5, shape = Remission)) +
                 geom_point(size=3,alpha=0.5) +
                 facet_wrap(~rxn, scale = "free")
    print(pp)

    pp <- ggplot(dstscls, aes(x=HB_Mayo_impu, y=X1)) +
        geom_point()+
        geom_smooth()+
        facet_wrap(~rxn, scale = "free")
    print(pp)
    pp <- ggplot(dstscls, aes(x=HB_Mayo_impu, y=X2)) +
        geom_point()+
        geom_smooth()+
        facet_wrap(~rxn, scale = "free")
    print(pp)

}

```

