---
title: Statistical analysis of the count matrix of extracted reactions
author: Jan Taubenheim
date: "`r Sys.Date()`"
output: 
        html_document:
                toc: true
                theme: united
---


```{r setLogfile, eval =F}

log <- file(snakemake@log[[1]], open = "wt")
sink(log)
sink(log, type = "message")

```


```{r loadLibraries}

knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.width = 10, fig.height=5)

require(ggplot2)
require(data.table)
require(lme4)
require(lqmm)
require(car)
require(cowplot)
require(DT)
require(pheatmap)
require(limma)

```

```{r debug, eval=FALSE, include =FALSE}

# This section is only for debugging purposes
setClass("snakemake", representation(input = "list", output = "list"))
snakemake <- new("snakemake", 
                    input = list(
                        rxnCount = "results/data/ModelAnalysis/MatjesAbsorption.colormore22-rxnIdMat.csv",
                        subSysCount = "results/data/ModelAnalysis/MatjesAbsorption.colormore22-SubSysMat.csv",
                        lqmmModels = "results/data/FVA/MatjesAbsorption.colormore22-LQMMmodelsRangeFVA_zeroBiomass.csv",
                        rxn_stats = "results/data/FVA/MatjesAbsorption.colormore22-distFVA_constrvs~HB_Mayo_impu-PERMANOVAmodels.csv",
                        meta = "resources/META_emed_future.csv",
                        clinic = "resources/ClinicalData.csv",
                        subsysTable = "resources/Subsystems.csv",
                        sampleBlacklist = "resources/sampleBlacklist.csv",
                        GPR = "resources/colormore22_GPR.csv"
                    ),
                    output = list(
                        html = "results/reports/MatjesAbsorption.colormore22-Natrix_analyseRxnCounts.html"
                    )
                )

```


```{r}

meta <- fread(snakemake@input[["meta"]])
meta[,PatientID_Time := paste(PatientID, Time_seq, sep ="_")]
meta <- meta[Time_seq != -1,]
clinic <- fread(snakemake@input[["clinic"]], drop=1)
meta <- merge(meta,clinic, by="PatientID_Time", all.x=TRUE, suffix = c(".meta",""))
#meta_merge <- merge(meta,clinic, all.x=TRUE)

subSys <- fread(snakemake@input[["subSysCount"]])
subSysCount <- as.matrix(subSys[,-1, with =F])
rownames(subSysCount) <- gsub(" ","_",unlist(subSys[,1]))
rxns <- fread(snakemake@input[["rxnCount"]])
rxnCount <- as.matrix(rxns[,-1,with=F ])
rownames(rxnCount) <- gsub(" ","_",unlist(rxns[,1]))
subSystems <- fread(snakemake@input[["subsysTable"]])
GPR <- fread(snakemake@input[["GPR"]])

# remove degraded samples
blcklst <- fread(snakemake@input[["sampleBlacklist"]])
blckSmpls <- blcklst[relevance < 2, Sample]

meta <- meta[!(SeqID %in% blckSmpls),]
subSysCount <- subSysCount[,!(colnames(rxnCount) %in% blckSmpls)]
rxnCount <- rxnCount[,!(colnames(rxnCount) %in% blckSmpls)]
meta <- meta[SeqID %in% colnames(rxnCount),]

lqmmModels <- fread(snakemake@input[["lqmmModels"]])
rxnDistStats <- fread(snakemake@input[["rxn_stats"]])

```


```{r rxnHBMayo}


# than we can still use a simple wilcox test for each reaction (present/absence) to test association with HB_Mayo

trxnCount <- data.table(t(rxnCount), keep.rownames=TRUE)
rxn_wilcox <- merge(meta[Tissue == "Biopsy" & !is.na(HB_Mayo_impu),], 
                    trxnCount, 
                    by.x ="SeqID",
                    by.y="rn")

rxn <- rownames(rxnCount)[apply(rxnCount,1,sum)>0]
wcxTest <- data.frame(
                    log2FC = rep(NA, length(rxn)),
                    pval = rep(NA,length(rxn)),
                    padj = rep(NA,length(rxn)),
                    row.names = rxn)
for(r in rxn){
    sel <- rxn_wilcox[[r]]
    if(sum(sel) < length(sel)-3 & sum(sel) > 3){
        wcx <- wilcox.test(rxn_wilcox[sel, HB_Mayo_impu],
                           rxn_wilcox[!sel,HB_Mayo_impu])
        wcxTest[r,"pval"] <- wcx[["p.value"]]
        wcxTest[r,"log2FC"] <- mean(log2(rxn_wilcox[sel, HB_Mayo_impu]+1)) -
                           mean(log2(rxn_wilcox[!sel,HB_Mayo_impu]+1))
                    }
}
wcxTest[["padj"]] <- p.adjust(wcxTest[["pval"]], method = "BH")
wcxTest <- data.table(wcxTest,keep.rownames=TRUE)
wcxTest[,absLog2FC := abs(log2FC)]
wcxTest[,rxn_plot := factor(rn, level = rn[order(log2FC)])]

```

```{r venn}

vennMat <- matrix(FALSE,nrow=nrow(subSystems), ncol = 3, dimnames = list(rxns = subSystems[["rxns"]], test = c("presence","range","distance")))
vennMat[wcxTest[padj <= 0.05, rn], "presence"] <- TRUE
vennMat[lqmmModels[padj <= 0.05, variable], "range"] <- TRUE
vennMat[rxnDistStats[padj <= 0.05 & Variable == "HB_Mayo_impu", Rxn], "distance"] <- TRUE

limma::vennDiagram(vennMat)

vennSig <- vennMat[apply(vennMat,1,sum) == ncol(vennMat),]

# doing the cats by myself as some are not annotated which should be
ownCats <- c(rep("AA-transport",2),
             "",
             "AA-transport",
             "FA-transport",
             "Trypt. metabolism",
             "Bile acid synthesis",
             rep("Cytidine metabolism",2),
             rep("AA-transport",2))
setkey(GPR, "rxn")
names(ownCats) <- unique(GPR[rxn %in% rownames(vennSig),GPR])

vennSig <- data.frame(vennSig)
vennSig[["Pathway"]] <- ownCats[GPR[rownames(vennMat[apply(vennMat,1,sum) == ncol(vennMat),]),GPR]]
vennSig[is.na(vennSig[["Pathway"]]),"Pathway"] <- c("Trypt. metabolism","Cytidine metabolism","Trypt. metabolism")

# add the metrics
setkey(wcxTest,"rn")
vennSig[["Presence_log2FC"]] <- wcxTest[rownames(vennSig),log2FC]
setkey(lqmmModels,"Rxn_ori")
vennSig[["Range_coeff"]] <- lqmmModels[rownames(vennSig),coefficient]
setkey(rxnDistStats,"Rxn")
vennSig[["Dist_R2"]] <- rxnDistStats[rownames(vennSig),R2]

pp_log2FC <-ggplot(data = vennSig, aes(x = Pathway, y = Presence_log2FC, color = Pathway)) +
    geom_jitter(height=0, width = 0.25,size=2) +
    theme_bw() +
    theme(legend.position = "none")
pp_log2FC
pp_log2FCbar <-ggplot(data = vennSig[order(vennSig[["Pathway"]]),], aes(x=1:nrow(vennSig),y = Presence_log2FC, fill = Pathway)) +
    geom_bar(stat="identity")+
    theme_bw() +
    xlab("Rxns")+
    ylab("Fold change of HB/Mayo score on presence of rxn")+
    theme(axis.text.x = element_blank())
pp_log2FCbar
pp_coeff<-ggplot(data = vennSig, aes(x = Pathway, y = Range_coeff,color = Pathway)) +
    geom_jitter(height=0, width = 0.25,size=2)+
    theme_bw() +
    theme(legend.position = "none")
pp_coeff
pp_R2 <-ggplot(data = vennSig, aes(x = Pathway, y = Dist_R2,color =Pathway)) +
    geom_jitter(height=0, width = 0.25,size=2)+
    theme_bw() +
    theme(legend.position = "none")
pp_R2

pp <- cowplot::plot_grid(pp_log2FC,pp_coeff,pp_R2,ncol=3)
pp

vennSig2 <- data.table(vennSig, keep.rownames =TRUE)
vennPlot <- vennSig2[,.(numberRxn = .N,mean_log2FC = mean(Presence_log2FC), mean_coeff = mean(Range_coeff), mean_R2 = mean(Dist_R2)), by = Pathway]
vennPlot[,n_genes := c(3,1,1,4,6)]

pp <- ggplot(data = vennPlot, aes(y=mean_coeff, x = mean_log2FC, size = mean_R2, color = Pathway)) +
    geom_point()
pp

pp_genesbar <- ggplot(data = vennPlot, aes(x=Pathway, y=n_genes, fill = Pathway)) +
    geom_bar(stat="identity") +
    ylab("Number of genes involved")+
    theme_bw() +
    theme(legend.position = "none",
          axis.text.x = element_blank())
pp_genesbar

pp_inset <- ggdraw() +
    draw_plot(pp_log2FCbar) +
    draw_plot(pp_genesbar, x=0.07,y=0.07, width=0.3,height=0.4)
pp_inset

```


