---
title: Statistical analysis of the range of an FVA analysis
author: Jan Taubenheim
date: "`r Sys.Date()`"
output: 
        html_document:
                toc: true
                theme: united
---

```{r log, eval=FALSE}

log <- file(snakemake@log[[1]], open = "wt")
sink(log)
sink(log, type = "message")

```

```{r loadLibraries}

knitr::opts_chunk$set(warning=TRUE, message=TRUE, fig.width = 10, fig.height=5)

require(ggplot2)
require(data.table)
#require(DT)
#require(ggdendro)
#require(ape)
require(vegan)
#require(cluster)

```


```{r debug, eval=FALSE, include = FALSE}

# This section is only for debugging purposes
setClass("snakemake", representation(input = "list",params = "list", output = "list"))
snakemake <- new("snakemake", 
                    input = list(
                        fva_dist ="results/data/FVA/MatjesAbsorption.colormore22_zeroBiomass_dist.csv" ,
                        rxn_stats = "results/data/FVA/MatjesAbsorption.colormore22-distFVA_zeroBiomassvs~HB_Mayo_impu-PERMANOVAmodels.csv",
                        meta = "resources/META_emed_future.csv",
                        clinic = "resources/ClinicalData.csv",
                        sampleBlacklist = "resources/sampleBlacklist.csv",
                        subsysTable = "resources/Subsystems.csv"
                    ),
                    params = list(
                        variable = "~HB_Mayo_impu"
                    ),
                    output = list(
                        html = "results/reports/MatjesAbsorption.colormore22-Natrix_analyseFVAdist.html"
                    )
                )

```


```{r loadData}

fva <- read.csv(snakemake@input[["fva_dist"]], row.names=1)

meta <- fread(snakemake@input[["meta"]])
meta[,PatientID_Time := paste(PatientID, Time_seq, sep ="_")]
meta <- meta[Time_seq != -1,]
clinic <- fread(snakemake@input[["clinic"]], drop=1)
meta <- merge(meta,clinic, by="PatientID_Time", all.x=TRUE, suffix = c(".meta",""))

# remove degraded samples
blcklst <- fread(snakemake@input[["sampleBlacklist"]])
blckSmpls <- blcklst[relevance < 2, Sample]

meta <- meta[!(SeqID %in% blckSmpls),]
meta <- meta[SeqID %in% colnames(fva),]
fva <- fva[meta[,SeqID],meta[,SeqID]]

subsys <- fread(snakemake@input[["subsysTable"]])
subsys[subSys =="", subSys := "Unknown"]

rxn_stats <- fread(snakemake@input[["rxn_stats"]])
table(rxn_stats[,Rxn] %in% subsys[,rxns])

variable <- gsub("^~","",snakemake@params[["variable"]])

```


# Clustering

The first idea is always to cluster the data with the distance measure.

```{r clustering}

# first use only the biopsy tissues
fva_biopsy <- fva[meta[Tissue == "Biopsy",SeqID],meta[Tissue == "Biopsy",SeqID]]
fva_scale <- cmdscale(as.dist(fva_biopsy))
colnames(fva_scale) <- c("MDS1","MDS2")
fva_scale <- merge(data.table(fva_scale, keep.rownames=TRUE), meta, by.x="rn",by.y="SeqID")
fva_pca <- prcomp(fva_biopsy)
fva_scale[,PC1 := fva_pca$x[,1]]
fva_scale[,PC2 := fva_pca$x[,2]]

pp <- ggplot(fva_scale, aes(x=MDS1, y=MDS2, color = HB_Mayo_impu<5, shape = Diagnosis)) +
    geom_point(size=3,alpha=0.5)
pp
pp <- ggplot(fva_scale, aes(x=MDS1, y=MDS2, color = as.factor(Time_seq), shape = Remission)) +
    geom_point(size=3, alpha=0.5)
pp

pp <- ggplot(fva_scale, aes(x=PC1, y=PC2, color = HB_Mayo_impu<5, shape =Diagnosis)) +
    geom_point(size=3,alpha=0.5)
pp
pp <- ggplot(fva_scale, aes(x=PC1, y=PC2, color = as.factor(Time_seq), shape =Remission)) +
    geom_point(size=3, alpha = 0.5)
pp



```

```{r dump, include = FALSE, eval = FALSE}

# cluster by mediods
fva_pam <- pam(fva_biopsy, 2, diss = TRUE) 
setkey(fva_scale, "rn")
fva_scale[names(fva_pam[["clustering"]]), PAM := fva_pam[["clustering"]]]
fva_scale[HB_Mayo_impu < 5,HB_Mayo_low := "low"]
fva_scale[HB_Mayo_impu > 4,HB_Mayo_low := "high"]
setkey(fva_scale, "rn")
fva_scale[fva_pam$medoids[1], HB_Mayo_low := "Mediod1"]
fva_scale[rn==fva_pam$medoids[2], HB_Mayo_low := "Mediod2"]

pp <- ggplot(fva_scale, aes(x=MDS1, y=MDS2, color = HB_Mayo_low, shape =factor(PAM))) +
    geom_point(size=3)
pp

pp <- ggplot(fva_scale, aes(x=factor(PAM), y=HB_Mayo_impu)) +
    geom_boxplot() +
    facet_grid(~Remission)
pp

pp <- ggplot(fva_scale, aes(x=factor(PAM), y=log(Time_seq+1))) +
    geom_boxplot() +
    facet_grid(~Remission)
pp

table(fva_scale[,.(PAM,Remission)])
table(fva_scale[,.(PAM,HB_Mayo_impu<5)])
fisher.test(table(fva_scale[,.(PAM,HB_Mayo_impu<5)]))

hc <- hclust(as.dist(fva_biopsy), method = "complete")
ori_labels <- hc[["labels"]]
hc[["labels"]] <- fva_scale[ori_labels, Remission]
plot(as.phylo(hc),
     tip.color = c("red","blue")[as.factor(fva_scale[ori_labels,HB_Mayo_impu<5])],
     type = "fan",
     main = "HB/Mayo in complete linkage hier. clustering")
legend("topright",
       title = "HB/Mayo < 5",
       legend = sort(c("TRUE","FALSE")),
       pch = 1,
       col = c("red","blue"))

hc[["labels"]] <- fva_pam[["clustering"]][ori_labels]
plot(as.phylo(hc),
     tip.color = c("red","blue")[as.factor(fva_scale[ori_labels,HB_Mayo_impu<5])],
     type = "fan",
     main = "HB/Mayo in complete linkage hier. clustering, PAM labels")
legend("topright",
       title = "HB/Mayo < 5",
       legend = sort(c("TRUE","FALSE")),
       pch = 1,
       col = c("red","blue"))

ctre <- cutree(hc, 4)
hc[["labels"]] <- ctre
plot(as.phylo(hc),
     tip.color = c("red","blue")[as.factor(fva_scale[ori_labels,HB_Mayo_impu<5])],
     type = "fan",
     main = "HB/Mayo in complete linkage hier. clustering, cutree labels")
legend("topright",
       title = "HB/Mayo < 5",
       legend = sort(c("TRUE","FALSE")),
       pch = 1,
       col = c("red","blue"))

mantel(as.dist(fva_biopsy), dist(fva_scale[rownames(fva_biopsy),HB_Mayo_impu]))
plot(as.dist(fva_biopsy), dist(fva_scale[rownames(fva_biopsy),HB_Mayo_impu]))

with(fva_scale[rownames(fva_biopsy),], adonis(as.dist(fva_biopsy)~PatientID+HB_Mayo_impu+Time_seq))
a<-adonis2(as.dist(fva_biopsy)~PatientID+HB_Mayo_impu, by="margin", data = fva_scale[rownames(fva_biopsy),], permutations=2000)


hist(unlist(fva_biopsy))

fva_biopsy_long <- as.data.frame(t(combn(rownames(fva_biopsy),2)))
fva_biopsy_long[["Distance"]] <- as.dist(fva_biopsy)
fva_biopsy_long <- data.table(fva_biopsy_long)

colnames(fva_biopsy_long) <- c("S1","S2", "Distance")
setkey(meta, "SeqID")
grp <-cbind(meta[fva_biopsy_long[,S1],Remission],
            meta[fva_biopsy_long[,S2],Remission])
grp <- t(apply(grp,1,sort))
grp <- paste(grp[,1],grp[,2], sep =" vs. ")
fva_biopsy_long[,Remission := grp]

grp <-cbind(meta[fva_biopsy_long[,S1],HB_Mayo_impu<5],
            meta[fva_biopsy_long[,S2],HB_Mayo_impu]<5)
grp <- t(apply(grp,1,sort))
grp <- paste(grp[,1],grp[,2], sep =" vs. ")
fva_biopsy_long[,HB_Mayo := grp]

```

# Rxn based stats

Lets see the results which result from the single reaction PERMANOVAs.

```{r rxnStats}

# sort after R2 value
rxn_sig <- rxn_stats[padj <= 0.05 & Variable ==variable,Rxn]

if(length(rxn_sig) > 0){

    ord <- order(rxn_stats[padj <= 0.05 & Variable ==variable,R2])
    rxn_plot <-  rxn_stats[padj<= 0.05 & Variable == variable,]
    rxn_plot[,Rxn := factor(Rxn, levels = unique(Rxn)[ord])]
    rxn_plot <- rxn_plot[Rxn %in% rxn_sig,]
    p_rxnstats <- ggplot(rxn_plot, aes(x=Rxn, y = R2, color = padj, shape = Variable)) + 
        geom_point() +
        theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
    print(p_rxnstats)

    rxn_plot <- merge(rxn_plot, subsys, by.x = "Rxn", by.y= "rxns")

    p_barplot <- ggplot(rxn_plot[Variable==variable,], aes(x=subSys,fill=subSys)) +
        geom_bar() +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 45, hjust=1, vjust=1),
              legend.position = "none")
    print(p_barplot)

    tab_subsys <- table(rxn_plot[Variable == variable, subSys])
    ratio_subsys <- table(subsys[,1])
    ratio_subsys <- tab_subsys/ratio_subsys[names(tab_subsys)]
    tab_subsys <- data.table(subsys = names(tab_subsys),count = as.vector(tab_subsys), ratio = as.vector(ratio_subsys))
    r2_mean <- rxn_plot[Variable ==variable, .(r2_mean = mean(R2)), by=subSys]
    tab_subsys <- merge(tab_subsys, r2_mean, by.x = "subsys",by.y="subSys")

    topcounts <- tab_subsys[count >= min(sort(count,decreasing=TRUE)[1:20]),]
    p_barplotTopcounts <- ggplot(topcounts, aes(x= subsys, y = count, fill = ratio)) +
        geom_bar(stat="identity",color = "black") +
        theme_bw() +
        scale_fill_gradient2(high="red") +
        theme(axis.text.x = element_text(angle = 45, hjust =1, vjust=1))
    print(p_barplotTopcounts)

    topratios <- tab_subsys[ratio >= min(sort(ratio,decreasing=TRUE)[1:20]),]
    p_barplotTopratio <- ggplot(topratios, aes(x= subsys, y = count, fill = ratio)) +
        geom_bar(stat="identity",color = "black") +
        theme_bw() +
        scale_fill_gradient2(high="red") +
        theme(axis.text.x = element_text(angle = 45, hjust =1, vjust=1))
    print(p_barplotTopratio)

    topr2 <- tab_subsys[r2_mean >= min(sort(r2_mean,decreasing=TRUE)[1:20]),]
    p_barplotTopr2 <- ggplot(topr2, aes(x= subsys, y = count, fill = r2_mean)) +
        geom_bar(stat="identity",color = "black") +
        theme_bw() +
        scale_fill_gradient2(high="red") +
        theme(axis.text.x = element_text(angle = 45, hjust =1, vjust=1))
    print(p_barplotTopr2)
} else {
    print("No significant reactions found")
}

```


